"""Normalized error codes (ARCH_AGENT_GATEWAY §10)."""

from __future__ import annotations

POLICY_DENY = "POLICY_DENY"
TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
TOOL_TIMEOUT = "TOOL_TIMEOUT"
MCP_CONNECT_ERROR = "MCP_CONNECT_ERROR"
MCP_TIMEOUT = "MCP_TIMEOUT"
ENGINE_ERROR = "ENGINE_ERROR"
ENGINE_NOT_INSTALLED = "ENGINE_NOT_INSTALLED"
VALIDATION_ERROR = "VALIDATION_ERROR"
